---
- name: Install jenkins
  hosts: all
  user: user
  sudo: True

  tasks:
  
    - name: Add repository key
      apt_key: 
        url='http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key'
        state=present
      environment:
        http_proxy: http://147.215.1.189:3128
    - name: Add repository
      apt_repository: 
        repo='deb http://pkg.jenkins-ci.org/debian binary/'
        update_cache=yes
      environment:
        http_proxy: http://147.215.1.189:3128
    - name: Install dependencies
      apt: 
        name={{item}}
        state=present
        update_cache=yes
        cache_valid_time=60
        install_recommends=no
      environment:
        http_proxy: http://147.215.1.189:3128
      with_items:
        - jenkins
